const express = require("express");
const router = express.Router();
const langMiddleware = require("../middleware/langMiddleware");
const aiRoutes = require("./aiRoutes");
const companionAdminRoutes = require("./admin/campanionAdmin");
const userAdminRoutes = require("./admin/userAdmin");
const familyAdminRoutes = require("./admin/familyAdmin");
const settingsAdminRoutes = require("./admin/settingsAdmin");
const reviewAdminRoutes = require("./admin/reviewsAdmin");
const authRoutes = require("./authRoutes");
const bookingRoutes = require("./bookingRoutes");
const bookingAdminRoutes = require("./admin/bookingAdmin");
const companionRoutes = require("./companion");
const familyRoutes = require("./family");
const chatRoutes = require("./chatRoutes");
const dashboardStatsRoutes = require("./admin/dashboradStats");
const activityAdminRoutes  = require("./admin/activityAdmin");
const reviewRoutes = require("./review");
const notificationRoutes = require("./notification");
const skillRoutes = require("./skillRoutes");
const jobPostRoutes = require("./jobPostRputes");
const proposalRoutes = require("./proposalRoutes");
const paymentRoutes = require("./paymentRoutes");
const uploadRoutes = require("./upload.routes");

// Apply localization middleware globally to all API routes
router.use(langMiddleware);

router.use("/admin/companions", companionAdminRoutes);
router.use("/admin/users", userAdminRoutes);
router.use("/admin/families", familyAdminRoutes);
router.use("/admin/settings", settingsAdminRoutes);
router.use("/admin/bookings", bookingAdminRoutes);
router.use("/admin/reviews", reviewAdminRoutes);
router.use("/admin/activity", activityAdminRoutes);
router.use("/admin", dashboardStatsRoutes);
router.use("/auth", authRoutes);
router.use("/ai", aiRoutes);
router.use("/bookings", bookingRoutes);
router.use("/companion", companionRoutes);
router.use("/family", familyRoutes);
router.use("/reviews", reviewRoutes);
router.use("/notifications", notificationRoutes);
router.use("/chat", chatRoutes);
router.use("/skills", skillRoutes);
router.use("/job-posts", jobPostRoutes);
router.use("/proposals", proposalRoutes);
router.use("/payments", paymentRoutes);
router.use("/upload", uploadRoutes);

module.exports = router;
