const express = require("express");
const router = express.Router();
const aiRoutes = require("./aiRoutes");
const companionAdminRoutes = require("./admin/campanionAdmin");
const userAdminRoutes = require("./admin/userAdmin");
const authRoutes = require("./authRoutes");
const bookingRoutes = require("./bookingRoutes");
const companionRoutes = require("./companion");
const familyRoutes = require("./family");
const chatRoutes = require("./chatRoutes");
const dashboardStatsRoutes = require("./admin/dashboradStats");
const reviewRoutes = require("./review");
const notificationRoutes = require("./notification");
const skillRoutes = require("./skillRoutes");
router.use("/admin/companions", companionAdminRoutes);
router.use("/admin/users", userAdminRoutes);
router.use("/admin", dashboardStatsRoutes);
router.use("/auth", authRoutes);
router.use("/ai", aiRoutes);
router.use("/bookings", bookingRoutes);
router.use("/companion", companionRoutes);
router.use("/family", familyRoutes);
router.use("/reviews", reviewRoutes);
router.use("/notifications", notificationRoutes);
router.use("/chat", chatRoutes);
router.use("/skills", skillRoutes);
module.exports = router;
